# Generated by Django 5.0.1 on 2024-05-14 11:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_delete_contact'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Comment',
        ),
    ]
