# Generated by Django 5.0.1 on 2024-05-14 12:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0013_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CustomUser',
        ),
    ]
